spring:
  application:
    name: forecast
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PW}
  jpa:
    hibernate:
      ddl-auto: create
#        Application 실행시 DB 초기화
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: true
    defer-datasource-initialization: true
    profiles:
      include: create
  logging:
    level:
      org.hibernate.SQL: debug
      org.springframework.jdbc: debug

openapi:
  forecast-key: 3zQSv0nZcHPFNenjAZIVL0h2XWwxqOCDCdTXwcQHbT6vrTX7uZu8b8c6SIY8IgzkBLbcSAEBgcUzLrzMTqfF3g%3D%3D

